#!/usr/bin/env python3
##
## EPITECH PROJECT, 2019
## 202unsold_2018
## File description:
## 203hotline
##

from sys import argv
from hotline import hotline_one, hotline_two
from binomial import error

def usage():
    """Print the helper in the standard output."""
    print('USAGE\n\t./203hotline [n k | d]',
    '\nDESCRIPTION\n\tn\t\x1B[3mn\x1B[23m value for the computation of (n k)',
    '\tk\t\x1B[3mk\x1B[23m value for the computation of (n k)',
    '\td\taverage duration of calls (in seconds)', sep='\n')

if __name__ == "__main__":
    if len(argv) == 2 and argv[1] == "-h":
        usage()
    elif len(argv) == 2 and argv[1].isnumeric():
        data = int(argv[1])
        hotline_one(data)
    elif len(argv) == 3 and argv[1].isnumeric() and argv[2].isnumeric():
        data = [int(argv[1]), int(argv[2])]
        hotline_two(data)
    else:
        error("INVALID ARGUMENT\n")
